FROM golang:1.25-alpine

RUN apk add --no-cache git

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY app/go.mod app/go.sum* ./
RUN go mod download

COPY app/ .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
